
// LOAD_USERS

export const LOAD_USERS ="LOAD_USERS";
export const LOAD_USERS_SUCCESS ="LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAILURE ="LOAD_USERS_FAILURE";
export const UPDATE_USER_SUCCESS ="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE="UPDATE_USER_FAILURE";
export const UPDATE_USER ="UPDATE_USER";
export const DELETE_USER ="DELETE_USER";
export const DELETE_USER_SUCCESS ="DELETE_USER_SUCCESS";
export const LOAD_USER_BY_ID= "LOAD_USER_BY_ID";
export const LOAD_USER_BY_ID_SUCCESS ="LOAD_USER_BY_ID_SUCCESS";

